#!/bin/bash
# annovar is special, we are going to fake a wget 
# and build it only once, if you want new versions
# tell the biobase people to properly publish 
# their code.  

source functions

annovar_url=""
annovar_type=""
