#!/bin/bash
# bowtie is a wget (sourceforge) type download

source functions

bowtie_url="sourceforge.net/projects"
bowtie_type="wget_source_forge"
bowtie_user="bowtie-bio"

automated_download "bowtie"
