#!/bin/bash
# bowtie2 is a wget (sourceforge) type download

source functions

bowtie2_url="sourceforge.net/projects/"
bowtie2_type="wget_source_forge"
bowtie2_user="bowtie-bio"

automated_download "bowtie2"
