#!/bin/bash
# clustalw is wget (see publishers) download  

source functions

clustalw_url="www.clustal.org/download/current/"
clustalw_type="wget_special"
clustalw_user=""

clustalw_latest () {
    curl $clustalw_url | grep -o "clustalw-[0-9]\.[0-9]\.tar\.gz" | uniq
	}

clustalw_wget_in_dir () {
	ver_info=`curl $clustalw_url | grep -o "clustalw-[0-9]\.[0-9]\.tar\.gz" | uniq
	( cd "${code_base_loc}/${1}" &&  echo $ver_info >> "${1}_data" )

	post_to_log "attempting to to wget ${1}"
	wget_call_loc="${clustalw_url}/${ver_info}"
	( cd "${code_base_loc}/${1}" && wget $wget_call_loc )
}

automated_download "clustal"

if [ $(current_download_version "clustal") -ne $(sicer_latest) ]; then
	post_to_log "latest for clustal on system and latest remote don't match, time for downloads"
	sicer_wget_in_dir "clustal"
else
	post_to_log "no new code found for clustalw, good jerb"
fi
