#!/bin/bash
# clustalw is wget (see publishers) download  

source functions

clustalw_url="www.clustal.org/download/current/"
clustalw_type="wget_special"
clustalw_user=""

automated_download "clustalw"
