#!/bin/bash
# cufflinks is a git (github) type download

source functions

cufflinks_url="api.github.com/repos/"
cufflinks_type="git_github"
cufflinks_user="cole-trapnell-lab"

automated_download "Cufflinks"
