#!/bin/bash
# cufflinks is a git (github) type download

source functions

Cufflinks_url="api.github.com/repos/"
Cufflinks_type="git_github"
Cufflinks_user="cole-trapnell-lab"

automated_download "Cufflinks"
