#!/bin/bash
# tophat is a wget (it's own) download
#| grep -o "tophat-2\.[0-9]\.[0-9]..tar.gz" | grep -v "tophat-2\.[0-9]\.[0-9]*[A-Za-z].tar.gz" | sed -e "s/-/ /g" -e "s/\./ /g" | sort -k4 -u | tail -n 1 | sed -e "s/ /-/" -e "s/ /\./g"

source functions

tophat_url="ccb.jhu.edu/software/tophat/downloads/"
tophat_type="wget_special"
tophat_user="tphat"

tophat_latest () { 
	curl $tophat_url | grep -o "tophat-2\.[0-9]\.[0-9]..tar.gz" | grep -v "tophat-2\.[0-9]\.[0-9]*[A-Za-z].tar.gz" | sed -e "s/-/ /g" -e "s/\./ /g" | sort -k4 -u | tail -n 1 | sed -e "s/ /-/" -e "s/ /\./g" 
}

tophat_wget_in_dir () {
	ver_info=`curl $tophat_url | grep -o "tophat-2\.[0-9]\.[0-9]..tar.gz" | grep -v "tophat-2\.[0-9]\.[0-9]*[A-Za-z].tar.gz" | sed -e "s/-/ /g" -e "s/\./ /g" | sort -k4 -u | tail -n 1 | sed -e "s/ /-/" -e "s/ /\./g"`
	( cd "${code_base_loc}/${1}" &&  echo $ver_info >> "${1}_data" )

	post_to_log "attempting to to wget ${1}"
	wget_call_loc="${tophat_url}/${ver_info}"
	( cd "${code_base_loc}/${1}" && wget $wget_call_loc )
}

automated_download "tophat"

if [ "$(current_download_version "tophat")" != "$(tophat_latest)" ]; then
	post_to_log "latest for tophat on system and latest remote don't match, time for downloads"
	tophat_wget_in_dir "tophat"
else
	post_to_log "no new code found for tophat, good jerb"
fi
