#!/bin/bash
# fastx_toolkit is a git (github) download

source functions

fastx_toolkit_url="api.github.com/repos/"
fastx_toolkit_type="git_github"
fastx_toolkit_user="Debian"

automated_download "fastx-toolkit"
