#!/bin/bash
# galaxy is a hg (bitbucket) download

source functions


galaxy_url="api.bitbucket.org/2.0/repositories/galaxy/"
galaxy_type="hg_bitbucket"
galaxy_user="galaxy-dist"

automated_download "galaxy"
