#!/bin/bash
# kent tools is a rsync

source functions

kenttools_url="hgdownload.cse.ucsc.edu/admin/exe/"
kenttools_type="wget_special"
kenttools_user="userApps"

kenttools_latest () { 
	curl $kenttools_url | grep -o "userApps\.v[0-9][0-9][0-9]\.src\.tgz" | sed -e "s/v/v /g" -e "s/\./ /g" | sort -k3 -u | tail -n 1 | sed -e "s/v /v/g" -e "s/ /\./g"
}

kenttools_wget_in_dir () {
	ver_info=`curl $kenttools_url | grep -o "userApps\.v[0-9][0-9][0-9]\.src\.tgz" | sed -e "s/v/v /g" -e "s/\./ /g" | sort -k3 -u | tail -n 1 | sed -e "s/v /v/g" -e "s/ /\./g"` 
	( cd "${code_base_loc}/${1}" &&  echo $ver_info >> "${1}_data" )

	post_to_log "attempting to to wget ${1}"
	wget_call_loc="${kentools_url}/${ver_info}"
	( cd "${code_base_loc}/${1}" && wget $wget_call_loc )					
}

automated_download "kenttools"

if [ $(current_download_version "kenttools") -ne $(kenttools_latest) ]; then
	post_to_log "latest for kenttools on the system and latest remote don't match, time for downloads"
	sicer_wget_in_dir "kenttools"
else
	post_to_log "no new code found for kenttools, good jerb"
fi
