#!/bin/bash
# libgtextutils is a git (github) download

source functions

libgtextutils_url="api.github.com/repos/"
libgtextutils_type="git_github"
libgtextutils_user="Debian"

automated_download "libgtextutils"
