#!/bin/bash
# memesuite is a wget (its own) download

source functions

memesuite_url="http://ebi.edu.au/ftp/software/MEME/index.html"
memesuite_type="wget_special"
memesuite_user="meme"

automated_download "memesuite"
