#!/bin/bash
# rseg is a wget (its own) download 

source functions

rseg_url="smithlabresearch.org/downloads/"
rseg_type="wget_special"
rseg_user="rseg"

rseg_latest () { 
	curl "${rseg_url}" | grep -o "rseg-[0-9].[0-9].[0-9].tar.gz" | head -n 1 
}

rseg_wget_in_dir () {
	ver_info=`curl "${rseg_url}" | grep -o "rseg-[0-9].[0-9].[0-9].tar.gz" | head -n 1`
	( cd "${code_base_loc}/rseg" &&  echo $ver_info >> "$rseg_data" )

	post_to_log "attempting to to wget rseg"
	wget_call_loc="${rseg_url}${ver_info}"
	( cd "${code_base_loc}/rseg" && wget $wget_call_loc )
}

automated_download "rseg"

if [ "$(current_download_version "rseg")" != "$(rseg_latest)" ]; then
	post_to_log "latest for rseg on system and latest remote don't match, time for downloads"
	rseg_wget_in_dir "rseg"
else
	post_to_log "no new code found for rseg, good jerb"
fi

