#!/bin/bash
# sam stat is a wget (sourceforge) download

source functions

samstat_url="sourceforge.net/projects/"
samstat_type="wget_special_forge"
samstat_user="samstat"

automated_download "samstat"
