#!/bin/bash
# samtools is a wget (sourceforge) download

source functions

samtools_url="sourceforge.net/projects/"
samtools_type="wget_source_forge"
samtools_user="samtools"

automated_download samtools
