#!/bin/bash
# subread is a wget (sourceforge) download

source functions

subread_url="sourceforge.net/projects/"
subread_type="wget_source_forge"
subread_user="subread"

automated_download "subread"
